Add pipeline level ci
mathysgrapotte/stimulus pull request #115
Opened 2024-05-03 17:22 UTC by JoseEspinosa

Another addition towards #95 completion.

2024-05-04 07:53 UTC, mathysgrapotte commented
It seems that stimulus is trying to run deep learning workflow on the GitHub actions, since this workload is too much, the ci actions get cancelled.

2024-05-06 08:59 UTC, alessiovignoli requested changes

2024-05-06 08:59 UTC, alessiovignoli commented on bin/launch_data_transformer.py
> +    if "transform" in config:
no we want to know if the key associated to tranform is not None, not that the keyword "transform" is in the config. for the moment let's leave it like it is.

```suggestion
    if config["transform"]: 
```

2024-05-06 12:12 UTC, alessiovignoli approved these changes

2024-05-06 12:32 UTC, merged